Vichy97/Route-Search

.github/workflows/BuildHealth.yml
This pr sets up a github action that runs on pull requests to run `./gradlew buildHealth`
=> Feat: Add github workflow for buildHealth task

build.gradle.kts, scripts/pre-commit
This pr sets up a git prehook that runs `ktlintCheck` to prevent improperly formatting code from being committed.
=> Feat: ktlint git prehook

app/build.gradle.kts, app/src/test/kotlin/com/routesearch/di/AppModuleTest.kt, build.gradle.kts, data/build.gradle.kts, data/local/build.gradle.kts, data/local/src/main/kotlin/com/routesearch/local/CommonTypeConverters.kt, data/local/src/main/kotlin/com/routesearch/local/LocalDataModule.kt, data/local/src/main/kotlin/com/routesearch/local/RouteSearchDataBase.kt, data/local/src/main/kotlin/com/routesearch/local/area/Area.kt, data/local/src/main/kotlin/com/routesearch/local/area/AreaDao.kt, data/local/src/main/kotlin/com/routesearch/local/area/AreaLocalDataSource.kt, data/local/src/main/kotlin/com/routesearch/local/area/AreaRoomDataSource.kt, data/src/main/kotlin/com/routesearch/data/AreaMapper.kt, data/src/main/kotlin/com/routesearch/data/DataModule.kt, data/src/main/kotlin/com/routesearch/data/DefaultAreaRepository.kt, gradle/libs.versions.toml, settings.gradle.kts
This pr adds a local data source backed by room to store Areas.
=> Feat: Add local Area data source

.github/workflows/BuildHealth.yml, .github/workflows/Gradle Build.yml, data/remote/build.gradle.kts, data/remote/src/main/kotlin/com/routesearch/network/RemoteDataModule.kt, data/remote/src/main/kotlin/com/routesearch/network/area/search/AreaSearchDataSource.kt, data/remote/src/main/kotlin/com/routesearch/network/area/search/AreaSearchResult.kt, data/remote/src/main/kotlin/com/routesearch/network/area/search/AreaSearchTypeSenseDataSource.kt, data/src/main/kotlin/com/routesearch/data/area/search/AreaSearchResult.kt, data/src/main/kotlin/com/routesearch/data/area/search/AreaSearchResultMapper.kt, data/src/main/kotlin/com/routesearch/data/area/search/AreaSearchService.kt, data/src/main/kotlin/com/routesearch/data/area/search/DefaultAreaSearchService.kt, gradle/libs.versions.toml
This pr sets up the TypeSense client and sets up services to search for areas.
=> Feat: Set up area search service

app/build.gradle.kts, app/src/main/kotlin/com/routesearch/MainActivity.kt, app/src/main/kotlin/com/routesearch/navigation/MainNavGraph.kt, gradle/libs.versions.toml
This pr sets up the main app scaffolding that houses the nav graph and top app bar.
=> feat: Set up main app scaffolding

app/build.gradle.kts, app/src/main/kotlin/com/routesearch/MainActivity.kt, app/src/main/kotlin/com/routesearch/di/AppModule.kt, gradle/libs.versions.toml, ui-common/build.gradle.kts, ui-common/src/main/kotlin/com/routesearch/ui/common/CommonUiModule.kt, ui-common/src/main/kotlin/com/routesearch/ui/common/snackbar/SnackbarEvent.kt, ui-common/src/main/kotlin/com/routesearch/ui/common/snackbar/SnackbarManager.kt
This pr add support for app level snackbars.
=> feat: Add support for app-level snackbars

app/build.gradle.kts, app/src/main/kotlin/com/routesearch/di/AppModule.kt, app/src/main/kotlin/com/routesearch/navigation/MainNavGraph.kt, data/build.gradle.kts, data/local/build.gradle.kts, data/remote/build.gradle.kts, gradle/libs.versions.toml, navigation/build.gradle.kts, navigation/src/main/kotlin/com/routesearch/navigation/Destination.kt, navigation/src/main/kotlin/com/routesearch/navigation/NavEvent.kt, navigation/src/main/kotlin/com/routesearch/navigation/NavigationModule.kt, navigation/src/main/kotlin/com/routesearch/navigation/Navigator.kt, settings.gradle.kts, ui-common/build.gradle.kts
This pr sets up a navigation framework for the app
=> feat: Navigation

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
This pr upgrades Gradle from 8.4-rc2 to 8.4
=> Build: Upgrade Gradle to 8.4

gradle.properties
This pr enables the experimental Kotlin K2 compiler.
=> Build: Enable Kotlin K2 compiler

app/build.gradle.kts, app/src/main/kotlin/com/routesearch/di/AppModule.kt, settings.gradle.kts, util/build.gradle.kts, util/coroutines/build.gradle.kts, util/coroutines/src/main/kotlin/com/routesearch/util/coroutines/CoroutinesModule.kt, util/coroutines/src/main/kotlin/com/routesearch/util/coroutines/Qualifiers.kt, util/src/main/kotlin/com/routesearch/util/UtilModule.kt
This pr sets up some util modules and sets up a Koin module to provide `CoroutineContext`
=> Feat: Coroutine Utils

features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt
Updated the area screen to show a list of climbs when there are no areas.
=> Feat: Add climb list to area screen

data/build.gradle.kts, data/local/build.gradle.kts, data/local/src/main/kotlin/com/routesearch/data/local/area/AreaLocalDataSource.kt, data/local/src/main/kotlin/com/routesearch/data/local/area/AreaRoomDataSource.kt, data/remote/build.gradle.kts, data/remote/src/main/kotlin/com/routesearch/data/remote/area/AreaApolloDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/area/AreaRemoteDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/area/search/AreaSearchDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/area/search/AreaSearchTypeSenseDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/climb/ClimbApolloDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/climb/ClimbRemoteDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/climb/search/ClimbSearchDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/climb/search/ClimbSearchTypeSenseDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/util/ExceptionUtils.kt, data/src/main/kotlin/com/routesearch/data/area/AreaRepository.kt, data/src/main/kotlin/com/routesearch/data/area/DefaultAreaRepository.kt, data/src/main/kotlin/com/routesearch/data/climb/ClimbRepository.kt, data/src/main/kotlin/com/routesearch/data/climb/DefaultClimbRepository.kt, data/src/main/kotlin/com/routesearch/data/search/DefaultSearchService.kt, data/src/main/kotlin/com/routesearch/data/search/SearchService.kt, features/build.gradle.kts, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewModel.kt, gradle/libs.versions.toml, settings.gradle.kts, util/common/build.gradle.kts, util/common/src/main/kotlin/com/routesearch/util/common/error/Error.kt, util/common/src/main/kotlin/com/routesearch/util/common/result/Result.kt, util/common/src/main/kotlin/com/routesearch/util/common/result/ResultExt.kt
This pr replaces the usages of Kotlin Result class with a custom Result class. This class uses a custom Error class instead of Exceptions for the failure case so that we can avoid working directly with exceptions in the domain or presentation layers. This pr also adds more logcat logging when exceptions occur.
=> Chore: Better error handling

app/src/main/kotlin/com/routesearch/navigation/MainNavGraph.kt, features/src/main/kotlin/com/routesearch/features/FeaturesModule.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbModule.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewModel.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewState.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewModel.kt, features/src/main/res/values/strings.xml
=> feat: Add climb screen

app/build.gradle.kts, data/remote/src/main/kotlin/com/routesearch/data/remote/area/search/AreaSearchTypeSenseDataSource.kt, data/remote/src/main/kotlin/com/routesearch/data/remote/climb/search/ClimbSearchResult.kt, data/src/main/kotlin/com/routesearch/data/search/SearchResults.kt, data/src/main/kotlin/com/routesearch/data/search/SearchResultsMapper.kt, detekt.yml, features/src/main/kotlin/com/routesearch/features/search/SearchScreen.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewModel.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewState.kt, features/src/main/res/values/strings.xml
This pr greatly improves the search screen UI and fixes a few bugs. 
Before | After
-------|-------
https://github.com/Vichy97/Route-Search/assets/11032718/358b4a84-0b9b-41d4-afb8-6f1a490eb1b2|https://github.com/Vichy97/Route-Search/assets/11032718/bf2c3a33-205a-4f7b-85f5-4495afd1ec53
=> Feat: Update Search Screen UI

data/src/main/kotlin/com/routesearch/data/climb/Climb.kt, data/src/main/kotlin/com/routesearch/data/climb/MetadataMapper.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewModel.kt, features/src/main/res/values/strings.xml, gradle/libs.versions.toml
Updated the climb screen ui to be in the same style as the area screen.
=> feat: update climb screen ui

build.gradle.kts, data/local/src/main/kotlin/com/routesearch/data/local/CommonTypeConverters.kt, data/local/src/main/kotlin/com/routesearch/data/local/area/Area.kt, data/remote/src/main/graphql/area_query.graphql, data/src/main/kotlin/com/routesearch/data/area/Area.kt, data/src/main/kotlin/com/routesearch/data/area/AreaMapper.kt, data/src/main/kotlin/com/routesearch/data/area/ClimbCountMapper.kt, data/src/main/kotlin/com/routesearch/data/area/GradeMapMapper.kt, data/src/main/kotlin/com/routesearch/data/area/MetadataMapper.kt, data/src/main/kotlin/com/routesearch/data/area/OrganizationMapper.kt, detekt.yml, features/build.gradle.kts, features/src/main/kotlin/com/routesearch/features/area/AreaPreviewParameterProvider.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbPreviewParameterProvider.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewModel.kt, features/src/main/kotlin/com/routesearch/features/common/intent/GeoIntent.kt, features/src/main/kotlin/com/routesearch/features/common/views/GradeChart.kt, features/src/main/kotlin/com/routesearch/features/common/views/ImagePlaceholder.kt, features/src/main/kotlin/com/routesearch/features/common/views/MetadataCard.kt, features/src/main/kotlin/com/routesearch/features/search/SearchScreen.kt, features/src/main/res/values/strings.xml, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, ui-common/src/main/kotlin/com/routesearch/ui/common/compose/modifier/IgnoreParentHorizontalPadding.kt
This pr reworks quite a bit of the Climb and Area Screens and moves a lot of the code to re-usable components that are shared.
=> Feat: UI improvements

data/local/src/main/kotlin/com/routesearch/data/local/area/Area.kt, data/local/src/main/kotlin/com/routesearch/data/local/climb/Climb.kt, data/remote/src/main/graphql/area_query.graphql, data/src/main/kotlin/com/routesearch/data/area/Area.kt, data/src/main/kotlin/com/routesearch/data/area/AreaClimbMapper.kt, data/src/main/kotlin/com/routesearch/data/area/AreaMapper.kt, features/src/main/kotlin/com/routesearch/features/area/AreaPreviewParameterProvider.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/common/views/ExpandableText.kt, features/src/main/res/values/strings.xml
This pr includes some minor ui improvements to the area screen such as updating the climb and area item subtitles and changing the description text.
=> Feat: More area screen improvements

data/build.gradle.kts, data/src/main/kotlin/com/routesearch/data/area/Area.kt, data/src/main/kotlin/com/routesearch/data/area/AreaClimbMapper.kt, data/src/main/kotlin/com/routesearch/data/area/AreaMapper.kt, data/src/main/kotlin/com/routesearch/data/area/GradeMapMapper.kt, data/src/main/kotlin/com/routesearch/data/area/OrganizationMapper.kt, data/src/main/kotlin/com/routesearch/data/climb/Climb.kt, data/src/main/kotlin/com/routesearch/data/climb/ClimbMapper.kt, data/src/main/kotlin/com/routesearch/data/climb/Grades.kt, data/src/main/kotlin/com/routesearch/data/climb/Pitch.kt, data/src/main/kotlin/com/routesearch/data/climb/PitchMapper.kt, data/src/main/kotlin/com/routesearch/data/location/Location.kt, data/src/main/kotlin/com/routesearch/data/search/SearchResults.kt, data/src/main/kotlin/com/routesearch/data/search/SearchResultsMapper.kt, features/build.gradle.kts, features/src/main/kotlin/com/routesearch/features/area/AreaPreviewParameterProvider.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewState.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbPreviewParameterProvider.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/common/views/GradeChart.kt, features/src/main/kotlin/com/routesearch/features/common/views/Images.kt, features/src/main/kotlin/com/routesearch/features/common/views/MetadataCard.kt, features/src/main/kotlin/com/routesearch/features/search/SearchScreen.kt, gradle/libs.versions.toml
This pr prevents recomposition from occurring when you scroll on the area screen. See individual commit messages for more in depth explanations.
=> Perf: Area screen performance improvements

app/build.gradle.kts, app/src/main/kotlin/com/routesearch/appversion/AppVersion.kt, app/src/main/kotlin/com/routesearch/appversion/DefaultAppVersionProvider.kt, app/src/main/kotlin/com/routesearch/di/AppModule.kt, features/build.gradle.kts, features/src/main/kotlin/com/routesearch/features/FeaturesModule.kt, features/src/main/kotlin/com/routesearch/features/about/AboutModule.kt, features/src/main/kotlin/com/routesearch/features/about/AboutScreen.kt, features/src/main/kotlin/com/routesearch/features/about/AboutViewModel.kt, features/src/main/kotlin/com/routesearch/features/about/AboutViewState.kt, features/src/main/res/values/strings.xml, settings.gradle.kts, util/app-version/build.gradle.kts, util/app-version/src/main/java/com/routesearch/util/appversion/AppVersionProvider.kt
Simple about screen with links to github and openBeta repos
=> Feat: About screen

features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbInfoCard.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbPreviewParameterProvider.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewModel.kt, features/src/main/kotlin/com/routesearch/features/common/views/MetadataCard.kt, features/src/main/res/values/strings.xml
Update climb screen to have more info available to the user, such as the grade, type, height, etc.
=> Feat: Update climb screen

app/src/main/AndroidManifest.xml, app/src/main/kotlin/com/routesearch/MainActivity.kt, ui-common/src/main/res/values/themes.xml
This xml is not necessary and requires pulling in the material library
=> Chore: Remove Themes.xml 

features/src/main/kotlin/com/routesearch/features/about/AboutScreen.kt, features/src/main/kotlin/com/routesearch/features/about/AboutViewModel.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewModel.kt, features/src/main/kotlin/com/routesearch/features/common/CommonUrls.kt, features/src/main/res/values/strings.xml
Added a clickable link to the open beta website in the description placeholder of areas and climbs
=> feat: Added openbeta link in description placeholder

data/local/src/main/kotlin/com/routesearch/data/local/search/SearchHistoryDataStore.kt
Fixed search screen recent search history ordering to be chronological
=> Fix: Search history ordering

data/src/main/kotlin/com/routesearch/data/search/DefaultSearchHistoryRepository.kt, data/src/main/kotlin/com/routesearch/data/search/SearchHistoryRepository.kt, features/src/main/kotlin/com/routesearch/features/common/views/ErrorPlaceholder.kt, features/src/main/kotlin/com/routesearch/features/search/SearchScreen.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewModel.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewState.kt, features/src/main/res/values/strings.xml
This pr adds proper loading and error states for the search screen. These replace the Snackbar with a visual error placeholder with a retry button.
=> Feat: Search screen error and loading states

app/build.gradle.kts, app/src/main/kotlin/com/routesearch/MainActivity.kt, features/src/main/kotlin/com/routesearch/features/common/views/ErrorPlaceholder.kt, features/src/main/kotlin/com/routesearch/features/search/SearchScreen.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewModel.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewState.kt, features/src/main/res/values/strings.xml
This PR fixes a bug where Snackbars would not be shown when requested.
=> Fix: Fix snackbar not showing when requested

features/src/main/kotlin/com/routesearch/features/search/SearchScreen.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewModel.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewState.kt
This pr has various improvements to the search screen. It fixes a few visual bugs, improves performance, and cleans up the code a bit.
=> Feat: Search screen improvements

features/build.gradle.kts, features/src/main/kotlin/com/routesearch/features/FeaturesModule.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewModel.kt, features/src/main/kotlin/com/routesearch/features/common/views/Images.kt, features/src/main/kotlin/com/routesearch/features/gallery/GalleryScreen.kt, features/src/main/kotlin/com/routesearch/features/gallery/GalleryViewModel.kt, features/src/main/kotlin/com/routesearch/features/imageviewer/ImageViewerModule.kt, features/src/main/kotlin/com/routesearch/features/imageviewer/ImageViewerScreen.kt, features/src/main/kotlin/com/routesearch/features/imageviewer/ImageViewerScreenArgs.kt, features/src/main/kotlin/com/routesearch/features/imageviewer/ImageViewerViewModel.kt, features/src/main/kotlin/com/routesearch/features/imageviewer/ImageViewerViewState.kt, gradle/libs.versions.toml
Added an image viewer screen that allows the user to view single images and zoom in for more detail
=> Feat: Add image viewer screen

features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewState.kt, features/src/main/res/values/strings.xml
This pr adds proper error states to the area screen
=> Feat: Area screen error states

app/build.gradle.kts, app/src/main/kotlin/com/routesearch/navigation/MainNavGraph.kt
Main nav graph now checks if the screen is already loading before each navigation
=> Fix: Fix duplicate navigation

features/build.gradle.kts, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewModel.kt, features/src/main/kotlin/com/routesearch/features/common/views/MarkdownView.kt, settings.gradle.kts, ui-common/src/main/kotlin/com/routesearch/ui/common/compose/AnnotatedStringExt.kt, util/markdown/build.gradle.kts, util/markdown/src/main/java/com/routesearch/util/markdown/MarkdownElement.kt, util/markdown/src/main/java/com/routesearch/util/markdown/MarkdownParser.kt, util/markdown/src/main/java/com/routesearch/util/markdown/processor/HeadingProcessor.kt, util/markdown/src/main/java/com/routesearch/util/markdown/processor/ListItemProcessor.kt, util/markdown/src/main/java/com/routesearch/util/markdown/processor/MarkdownLineProcessor.kt
Added a new module for markdown and views for handling markdown elements from areas and climbs
=> Feat: Markdown Support

data/src/main/kotlin/com/routesearch/data/media/MediaMapper.kt, features/build.gradle.kts, features/src/main/kotlin/com/routesearch/features/common/views/ImagePlaceholder.kt, features/src/main/kotlin/com/routesearch/features/common/views/Images.kt
This pr fixes images failing to load as well as adds some logging and a placeholder when image requests fail.
=> Fix: Failed image requests

app/build.gradle.kts, build.gradle.kts, data/local/build.gradle.kts, data/remote/build.gradle.kts, features/build.gradle.kts, gradle/libs.versions.toml
This pr does some minor cleanup for our build scripts.
=> Build: Build script cleanup

data/local/src/main/kotlin/com/routesearch/data/local/area/Area.kt, data/local/src/main/kotlin/com/routesearch/data/local/climb/Climb.kt, data/local/src/main/kotlin/com/routesearch/data/local/climb/Pitch.kt, data/src/main/kotlin/com/routesearch/data/area/Area.kt, data/src/main/kotlin/com/routesearch/data/area/AreaClimbMapper.kt, data/src/main/kotlin/com/routesearch/data/area/AreaMapper.kt, data/src/main/kotlin/com/routesearch/data/climb/Climb.kt, data/src/main/kotlin/com/routesearch/data/climb/ClimbMapper.kt, data/src/main/kotlin/com/routesearch/data/climb/GradeExt.kt, data/src/main/kotlin/com/routesearch/data/climb/GradesMapper.kt, data/src/main/kotlin/com/routesearch/data/climb/Pitch.kt, data/src/main/kotlin/com/routesearch/data/climb/PitchMapper.kt, data/src/main/kotlin/com/routesearch/data/climb/TypeMapper.kt, features/src/main/kotlin/com/routesearch/features/area/AreaPreviewParameterProvider.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbInfoCard.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbPreviewParameterProvider.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt
Added support for climbs with multiple types
=> Feat: Add multiple type support for area and climb screens

features/src/main/kotlin/com/routesearch/features/about/AboutScreen.kt, features/src/main/kotlin/com/routesearch/features/about/AboutViewModel.kt, features/src/main/kotlin/com/routesearch/features/area/AreaScreen.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbScreen.kt, features/src/main/kotlin/com/routesearch/features/climb/ClimbViewModel.kt, features/src/main/kotlin/com/routesearch/features/common/CommonUrls.kt, features/src/main/kotlin/com/routesearch/features/common/views/MarkdownView.kt, features/src/main/kotlin/com/routesearch/features/common/views/MetadataCard.kt, features/src/main/kotlin/com/routesearch/features/organization/OrganizationDialog.kt, features/src/main/kotlin/com/routesearch/features/organization/OrganizationViewModel.kt, features/src/main/kotlin/com/routesearch/features/search/SearchScreen.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewModel.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewState.kt, features/src/main/res/values/strings.xml, ui-common/src/main/kotlin/com/routesearch/ui/common/compose/AnnotatedStringExt.kt
This PR updates some deprecated Material3 Composables.
=> Chore: Update deprecated compose usages

app/build.gradle.kts, app/src/main/kotlin/com/routesearch/RouteSearchApplication.kt, data/build.gradle.kts, data/src/main/kotlin/com/routesearch/data/DataModule.kt, data/src/main/kotlin/com/routesearch/data/image/CoilImageLoader.kt, data/src/main/kotlin/com/routesearch/data/image/ImageLoader.kt, data/src/main/kotlin/com/routesearch/data/image/ImageModule.kt, features/src/main/kotlin/com/routesearch/features/area/AreaViewModel.kt, features/src/main/kotlin/com/routesearch/features/common/views/Images.kt, gradle/libs.versions.toml, util/common/src/main/kotlin/com/routesearch/util/common/exception/ImageLoadingException.kt
Added Coil image caching for faster gallery screen transition
=> Feat: Pre cache images

features/src/main/kotlin/com/routesearch/features/about/AboutScreen.kt, features/src/main/kotlin/com/routesearch/features/about/AboutTransitions.kt, features/src/main/kotlin/com/routesearch/features/search/SearchScreen.kt, features/src/main/kotlin/com/routesearch/features/search/SearchViewModel.kt, features/src/main/res/values/strings.xml
Added an about screen button to the search screen
=> Feat: Add about screen button
